### ISSUE TITLE
Feature request: Queuing 

### ISSUE THREAD

**Issue by bangert** [andviro/grayproxy#3]
https://github.com/andviro/grayproxy/blob/a069b22fdfb5a1a303e9d1f047395f6068def19e/app.go#L119

it says 
```
// TODO: message buffering on disk
```

**Comment by bangert** [comment]
I might take a stab at this and was looking at using
https://github.com/beeker1121/goque

for this. Or did you have other plans?
Thanks

**Comment by andviro** [comment]
I had in mind something like boltdb, but goque look promising. By all means, go for it, I'll be happy to receive PR :)

**Comment by andviro** [comment]
Added simple persistence using [go-diskqueue](https://github.com/nsqio/go-diskqueue)

**Comment by bangert** [comment]
Thank you. Really appreciate it!

**Comment by andviro** [comment]
Great, glad to hear. Will be happy to know your thoughts in the future. As it is, it pretty much does all I want, but there's always room for improvement.
