### ISSUE TITLE
Using grayproxy without Docker

### ISSUE THREAD

**Issue by zurborg** [andviro/grayproxy#4]
Is there a way to compile a static linked version of grayproxy?

**Comment by andviro** [comment]
Hi there! Is there any problem with standard `go get github.com/andviro/grayproxy`? 
I was fairly careful to not include shared-linked libraries, and Go builds are static by default. You'll need a Go compiler, obviously :)

**Comment by zurborg** [comment]
If I do so, I get an error:
```
$ go get github.com/andviro/grayproxy
# github.com/andviro/grayproxy/vendor/github.com/go-mixins/http
src/github.com/andviro/grayproxy/vendor/github.com/go-mixins/http/server.go:46: hs.Shutdown undefined (type http.Server has no field or method Shutdown)
```
I'm using `go version go1.7.4 linux/amd64`

**Comment by andviro** [comment]
Graceful shutdown is a feature added to standard library in Go 1.8+.  I'll include minimum Go version into README, meanwhile please upgrade your compiler and all will be well.

**Comment by zurborg** [comment]
It's a bit complicated on debian, but I managed it. Thanks!

**Comment by andviro** [comment]
Don't mention it. I'll try to make a binary releases page to avoid situations like this in the future.
